name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Build image
        run: podman build -t localhost/cloud-native-server .

      - name: Authenticate to container registry
        env: 
             REGISTRY_USER: ${{ secrets.registry_user }}
             REGISTRY_PASS: ${{ secrets.registry_pass }}
        run: podman login -u $REGISTRY_USER --password $REGISTRY_PASS docker.io

      - name: Push image
        run: podman push localhost/cloud-native-server docker.io/imbev/cloud-native-server:latest

